import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-4 border-b border-black/[.08] bg-white px-6 py-3 text-sm dark:border-white/[.145] dark:bg-black">
          <Link href="/" className="text-zinc-700 hover:underline dark:text-zinc-300">
            Chat
          </Link>
          <Link
            href="/classify"
            className="text-zinc-700 hover:underline dark:text-zinc-300"
          >
            Classify
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
